server {
    listen 80;
    server_name leandro_odetto.midominio.com; # O la IP/host que te indique el profe

    root /home/alumno/lemp-sites/ulises_cabrera/repo_ulicab01;
    index index.php index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.3-fpm.sock; # Ver versión PHP instalada
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
